---
# tasks file for docker_wordpress
# start all needed joomla container

- name: '{{ app_name }} | include vars'
  include_vars: "{{ item }}"
  loop:
    - group_vars/wordpress.yml

- name: '{{ app_name }} | include directory structure'
  include_tasks: directory_structure.yml

- name: '{{ app_name }} | wordpress network'
  include_tasks: network.yml

- name: '{{ app_name }} | docker database'
  include_tasks: create_app_{{ app_db_type }}_container.yml

- name: '{{ app_name }} | docker wordpress'
  include_tasks: wordpress.yml

- name: '{{ app_name }} | docker nginx'
  include_tasks: nginx.yml
  when: "'fpm' in app_docker_image"

- name: '{{ app_name }} | backup nextcloud'
  include_tasks: tasks/backup_script.yml
  when: backup_enabled
